name: opencoolapk
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.7
  crypto: ^2.0.6
  uuid: ^2.0.2
  pull_to_refresh: ^1.4.5
  carousel_slider: any
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true